# Generated by Django 2.1.5 on 2019-03-15 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.model_fields
import main.utilities


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20190206_0149'), ('main', '0003_auto_20190218_2217'), ('main', '0004_delete_repeatingevent'), ('main', '0005_auto_20190221_2320'), ('main', '0006_auto_20190222_1812'), ('main', '0007_remove_worktimecommitment_date'), ('main', '0008_auto_20190225_1253'), ('main', '0009_auto_20190302_1446'), ('main', '0010_auto_20190303_2100'), ('main', '0011_auto_20190311_1800'), ('main', '0012_auto_20190311_1851'), ('main', '0013_shift_classroom'), ('main', '0014_auto_20190314_1645'), ('main', '0015_auto_20190314_1704'), ('main', '0016_auto_20190314_1712')]

    initial = True

    dependencies = [
        ('people', '0005_auto_20190218_2217'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekday', main.model_fields.WeekdayField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareDayAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('end', models.DateTimeField(default=main.utilities.in_a_week)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('careday', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CareDay')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExtraCareDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(days=112))),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom')),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekday', main.model_fields.WeekdayField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift')),
                ('rank', models.IntegerField(choices=[(1, 'best'), (2, 'pretty good'), (3, 'acceptable')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='WorktimeCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.NullBooleanField()),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomShiftSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
            preserve_default=False,
        ),
    ]
