# Generated by Django 2.1.5 on 2019-02-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimeassignment',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='worktimeassignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period'),
        ),
        migrations.AddField(
            model_name='worktimeassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
        migrations.AddField(
            model_name='shiftinstance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
        ),
        migrations.AddField(
            model_name='shiftinstance',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Child'),
        ),
        migrations.AddField(
            model_name='shiftinstance',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
        migrations.AddField(
            model_name='period',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
        ),
        migrations.AddField(
            model_name='extracareday',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='cancelledcareday',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
    ]
