# Generated by Django 2.1.5 on 2019-02-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190218_2217'),
        ('main', '0004_delete_repeatingevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorktimeAssignment',
            new_name='ShiftAssignment',
        ),
    ]
