# Generated by Django 2.1.5 on 2019-03-02 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import main.model_fields
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190218_2217'),
        ('main', '0008_auto_20190225_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDayContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', recurrence.fields.RecurrenceField()),
                ('ends', recurrence.fields.RecurrenceField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomShiftSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom')),
            ],
        ),
        migrations.AlterModelOptions(
            name='careday',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='caredayassignment',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='extracareday',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='happening',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='worktimecommitment',
            options={'ordering': ['start', 'end']},
        ),
        migrations.RemoveField(
            model_name='careday',
            name='extended_endtime',
        ),
        migrations.RemoveField(
            model_name='extracareday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='extracareday',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='happening',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='happening',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='happening',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='happening',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='period',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 2, 14, 46, 19, 957653, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 2, 14, 46, 27, 446278, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='weekday',
            field=main.model_fields.WeekdayField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracareday',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extracareday',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='happening',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='happening',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='holiday',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='holiday',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='period',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='period',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
