# Generated by Django 2.1.5 on 2019-03-03 21:00

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190302_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareDayContract',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='careday',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='extended',
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='caredays',
            field=models.ManyToManyField(to='main.CareDay'),
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='end',
            field=models.DateTimeField(default=main.models.in_a_week),
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='is_cancellation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
