# Generated by Django 2.1.5 on 2019-03-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190218_2217'),
        ('main', '0012_auto_20190311_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
            preserve_default=False,
        ),
    ]
