# Generated by Django 2.1.5 on 2019-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_shift_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftpreference',
            name='status',
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='rank',
            field=models.IntegerField(choices=[(1, 'best'), (2, 'pretty good'), (3, 'acceptable')], default=3),
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='status',
            field=models.IntegerField(choices=[(1, 'complete'), (2, 'incomplete'), (3, 'excused')], default=0),
        ),
    ]
