# Generated by Django 2.1.5 on 2019-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190314_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='status',
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='completed',
            field=models.NullBooleanField(),
        ),
    ]
