# Generated by Django 2.1.5 on 2019-03-16 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimecommitment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 16, 15, 0, 41, 516068, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
            preserve_default=False,
        ),
    ]
