# Generated by Django 2.1.4 on 2019-01-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpreference',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ShiftTime'),
        ),
        migrations.AddField(
            model_name='period',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
        ),
        migrations.AddField(
            model_name='familycommitment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FamilyAssignment'),
        ),
        migrations.AddField(
            model_name='familycommitment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
        migrations.AddField(
            model_name='familyassignment',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='familyassignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period'),
        ),
        migrations.AddField(
            model_name='familyassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
        ),
    ]
