# Generated by Django 2.1.4 on 2019-01-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('main', '0002_auto_20190111_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Shift')),
            ],
        ),
        migrations.RemoveField(
            model_name='familycommitment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='familycommitment',
            name='shift',
        ),
        migrations.AddField(
            model_name='familycommitment',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AddField(
            model_name='familycommitment',
            name='shift_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.ShiftInstance'),
        ),
    ]
