# Generated by Django 2.1.5 on 2019-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190316_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='worktimecommitment',
            name='shift',
        ),
    ]
