# Generated by Django 2.1.5 on 2019-02-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190218_2217'),
        ('main', '0002_auto_20190206_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorktimeCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('date', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
            ],
        ),
        migrations.RemoveField(
            model_name='cancelledcareday',
            name='child',
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='shiftinstance',
            name='shift',
        ),
        migrations.AlterModelOptions(
            name='happening',
            options={'ordering': ['start_date', 'start_time', 'end_date']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start_date', 'start_time', 'end_date']},
        ),
        migrations.RemoveField(
            model_name='shiftpreference',
            name='rank',
        ),
        migrations.AddField(
            model_name='happening',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='status',
            field=models.IntegerField(choices=[(0, 'incomplete'), (1, 'complete'), (2, 'excused')], default=0),
        ),
        migrations.DeleteModel(
            name='CancelledCareDay',
        ),
        migrations.DeleteModel(
            name='ShiftInstance',
        ),
    ]
