# Generated by Django 2.1.4 on 2019-01-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190111_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycommitment',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child'),
        ),
        migrations.AlterField(
            model_name='familycommitment',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ShiftInstance'),
        ),
    ]
