# Generated by Django 2.1.5 on 2019-03-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190316_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimecommitment',
            name='shift',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.Shift'),
            preserve_default=False,
        ),
    ]
