# Generated by Django 2.1.5 on 2019-02-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190218_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepeatingEvent',
        ),
    ]
