# Generated by Django 2.1.5 on 2019-03-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190318_1447'),
        ('main', '0004_worktimecommitment_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='careday',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Classroom'),
            preserve_default=False,
        ),
    ]
