# Generated by Django 2.1.4 on 2019-01-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190111_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familycommitment',
            name='assignment',
        ),
    ]
