# Generated by Django 2.1.4 on 2019-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_familycommitment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftinstance',
            name='date',
            field=models.DateField(),
        ),
    ]
