# Generated by Django 2.1.5 on 2019-02-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190221_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktimecommitment',
            options={'ordering': ['start_date', 'start_time', 'end_date']},
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktimecommitment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
