# Generated by Django 2.1.4 on 2019-01-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190111_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familycommitment',
            options={'ordering': ['shift_instance']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['weekday', 'shift_time']},
        ),
        migrations.AlterModelOptions(
            name='shiftinstance',
            options={'ordering': ['date', 'shift']},
        ),
        migrations.AlterModelOptions(
            name='shifttime',
            options={'ordering': ['start_time']},
        ),
    ]
