# Generated by Django 2.1.4 on 2019-01-16 14:37

from django.db import migrations, models
import django.db.models.deletion
import main.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190115_1607'),
        ('main', '0007_auto_20190115_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', main.model_fields.WeekdayField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('extended_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CareDayContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
            ],
        ),
    ]
