# Generated by Django 2.1.5 on 2019-02-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_worktimecommitment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careday',
            options={},
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='weekday',
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='careday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CareDay'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktimecommitment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
