# Generated by Django 2.1.4 on 2019-01-16 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_careday_caredaycontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDayTimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'ordering': ['start_time'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='careday',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['weekday', 'time_span']},
        ),
        migrations.RemoveField(
            model_name='careday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='careday',
            name='extended_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_time',
        ),
        migrations.AddField(
            model_name='careday',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='careday',
            name='name',
            field=models.CharField(default='nameless careday', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShiftTime',
        ),
        migrations.AddField(
            model_name='shift',
            name='time_span',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.ShiftTimeSpan'),
            preserve_default=False,
        ),
    ]
