# Generated by Django 2.1.4 on 2019-01-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190116_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careday',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='caredaytimespan',
            name='extended_duration',
        ),
        migrations.RemoveField(
            model_name='shifttimespan',
            name='duration',
        ),
        migrations.AddField(
            model_name='careday',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 16, 15, 46, 13, 855773)),
        ),
        migrations.AddField(
            model_name='caredaytimespan',
            name='extended_endtime',
            field=models.TimeField(default=datetime.time(17, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttimespan',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 16, 15, 46, 13, 855773)),
        ),
    ]
