# Generated by Django 2.1.5 on 2019-04-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190405_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.ShiftAssignmentCollection'),
            preserve_default=False,
        ),
    ]
