# Generated by Django 2.1.4 on 2019-01-16 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190116_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caredaytimespan',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='caredaytimespan',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 16, 15, 54, 17, 438621)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredaytimespan',
            name='name',
            field=models.CharField(default='nameless careday timespan', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caredaytimespan',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 55, 21, 284213)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careday',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifttimespan',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
