# Generated by Django 2.1.5 on 2019-03-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190303_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caredayassignment',
            name='caredays',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='caredayassignment',
            name='is_cancellation',
        ),
        migrations.AddField(
            model_name='caredayassignment',
            name='careday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CareDay'),
            preserve_default=False,
        ),
    ]
