# Generated by Django 2.1.5 on 2019-04-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190405_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='duration',
        ),
    ]
