# Generated by Django 2.1.4 on 2019-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190116_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careday',
            options={},
        ),
        migrations.RemoveField(
            model_name='careday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='careday',
            name='name',
        ),
        migrations.RemoveField(
            model_name='careday',
            name='start_time',
        ),
    ]
