# Generated by Django 2.1.4 on 2019-01-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190116_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='careday',
            name='time_span',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.CareDayTimeSpan'),
            preserve_default=False,
        ),
    ]
