# Generated by Django 2.1.5 on 2019-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190414_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, 'best'), (2, 'pretty good'), (3, 'acceptable')], default=3, null=True),
        ),
    ]
