# Generated by Django 2.1.4 on 2019-01-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190115_1607'),
        ('main', '0013_careday_time_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDayAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended', models.BooleanField(default=False)),
                ('careday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CareDay')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
            ],
        ),
        migrations.RemoveField(
            model_name='caredaycontract',
            name='child',
        ),
        migrations.DeleteModel(
            name='CareDayContract',
        ),
    ]
