# Generated by Django 2.1.4 on 2019-01-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190115_1607'),
        ('main', '0015_auto_20190117_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyCommitment',
            new_name='WorktimeCommitment',
        ),
    ]
