# Generated by Django 2.1.5 on 2019-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190516_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentchangenotice',
            name='_shift',
        ),
        migrations.RemoveField(
            model_name='commitmentchangenotice',
            name='child',
        ),
        migrations.RemoveField(
            model_name='commitmentcreation',
            name='_shift',
        ),
        migrations.RemoveField(
            model_name='commitmentcreation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='commitmentdeletion',
            name='_shift',
        ),
        migrations.RemoveField(
            model_name='commitmentdeletion',
            name='child',
        ),
        migrations.DeleteModel(
            name='CommitmentChangeNotice',
        ),
        migrations.DeleteModel(
            name='CommitmentCreation',
        ),
        migrations.DeleteModel(
            name='CommitmentDeletion',
        ),
    ]
