# Generated by Django 2.1.5 on 2019-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190517_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomshiftschedule',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='extracareday',
            name='child',
        ),
        migrations.AlterField(
            model_name='happening',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktimecommitment',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shiftpreference',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ClassroomShiftSchedule',
        ),
        migrations.DeleteModel(
            name='ExtraCareDay',
        ),
    ]
