# Generated by Django 2.1.4 on 2019-01-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190117_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDayInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('care_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CareDay')),
            ],
        ),
        migrations.CreateModel(
            name='Happening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='start',
            new_name='start_date',
        ),
    ]
