# Generated by Django 2.1.5 on 2019-08-08 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190605_1753'),
        ('main', '0017_auto_20190723_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=(main.models._ShiftOffsetMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorktimeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignments', models.ManyToManyField(to='main.ShiftAssignable')),
            ],
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='child',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shiftassignmentcollection',
            name='period',
        ),
        migrations.AlterModelOptions(
            name='happening',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='worktimecommitment',
            options={'ordering': ['start']},
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Period'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shiftpreference',
            unique_together={('child', 'shift', 'period')},
        ),
        migrations.DeleteModel(
            name='ShiftAssignment',
        ),
        migrations.DeleteModel(
            name='ShiftAssignmentCollection',
        ),
        migrations.AddField(
            model_name='worktimeschedule',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period'),
        ),
        migrations.AddField(
            model_name='shiftassignable',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ShiftPreference'),
        ),
    ]
