# Generated by Django 2.1.5 on 2019-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190808_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignable',
            name='offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignable',
            name='offset_modulus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
