# Generated by Django 2.1.5 on 2019-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190808_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimeschedule',
            name='committed',
            field=models.BooleanField(default=False),
        ),
    ]
