# Generated by Django 2.1.5 on 2019-08-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190605_1753'),
        ('main', '0020_worktimeschedule_committed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPreferenceNoteForPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Child')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
            ],
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
