# Generated by Django 2.1.5 on 2019-08-15 13:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190811_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignable',
            options={'ordering': ['preference', 'offset']},
        ),
        migrations.RenameField(
            model_name='shiftpreferencenoteforperiod',
            old_name='note',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='happening',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.DateTimeField(default=main.models.Period.start_default),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
