# Generated by Django 2.1.5 on 2019-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190815_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignable',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='worktimeschedule',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='worktimeschedule',
            name='period',
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='_active_offsets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shiftpreference',
            name='modulus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftpreference',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, 'best'), (2, 'pretty good'), (3, 'acceptable')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='ShiftAssignable',
        ),
        migrations.DeleteModel(
            name='WorktimeSchedule',
        ),
    ]
