# Generated by Django 2.1.5 on 2019-08-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190815_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftpreference',
            old_name='modulus',
            new_name='_modulus',
        ),
    ]
