# Generated by Django 2.1.5 on 2019-08-16 19:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190815_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='preference_deadline',
            field=models.DateTimeField(default=main.models.Period.start_default, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
