# Generated by Django 2.1.4 on 2019-01-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkEmailToObject',
            new_name='RelateEmailToObject',
        ),
    ]
