# Generated by Django 2.1.4 on 2019-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='shifts_per_month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('short_name', 'classroom'), ('first_name', 'last_name', 'classroom')},
        ),
    ]
