# Generated by Django 2.1.4 on 2019-01-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190115_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='schedulers',
            new_name='scheduler_set',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='teachers',
            new_name='teacher_set',
        ),
    ]
