# Generated by Django 2.1.4 on 2019-01-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190103_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinvite',
            name='token',
            field=models.CharField(default='default_token_aifhaoef', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
    ]
