# Generated by Django 2.1.4 on 2019-01-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190115_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parents',
            new_name='parent_set',
        ),
    ]
