# Generated by Django 2.1.4 on 2019-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190123_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateemailtoobject',
            name='relation_name',
            field=models.CharField(default='nameless-relation', max_length=50),
            preserve_default=False,
        ),
    ]
