# Generated by Django 2.1.5 on 2019-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
