# Generated by Django 2.1.5 on 2019-04-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_classroom_solicits_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='solicits_preferences',
        ),
    ]
