# Generated by Django 2.1.5 on 2019-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190420_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_set',
            field=models.ManyToManyField(related_name='bearers', to='people.Role'),
        ),
    ]
