# Generated by Django 2.1.5 on 2019-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_user_role_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_role',
            new_name='_active_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_set',
            field=models.ManyToManyField(related_name='_bearers', to='people.Role'),
        ),
    ]
