# Generated by Django 2.1.5 on 2019-06-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190527_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_set',
            new_name='_role_set',
        ),
    ]
