# Generated by Django 2.1.5 on 2019-08-22 13:51

from django.db import migrations, models
import people.skins


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190605_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skin',
            field=models.TextField(default=people.skins.date_seeded_skin),
        ),
    ]
