# Generated by Django 2.1.5 on 2019-02-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_active_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='people.Role'),
        ),
    ]
