# Generated by Django 2.1.5 on 2019-02-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_user__active_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_active_role',
            new_name='active_role',
        ),
    ]
